version : "3.8"

services:
  service1:
    image: image1
    ports: 
      - "5000:5000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 3s
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
        reservations:
          cpus: "0.5"
          memory: "500M"


