version : "3.8"

services:
  backend:
    image: backend
    ports: 
      - "5000:5000"
    networks:
      - mynetwork
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  mynetwork:
    driver: overlay