version: "3.8"
services:
    neptune-backend-service:
        image: programminghero1/prod-neptune-web-backend:1.1.4
        ports:
            - 5000:5000
        environment: []
        networks: []
        volumes: []
        deploy:
            replicas: 2
            resources:
                limits:
                    cpus: "0.5"
                    memory: 1G
                reservations:
                    cpus: "0.5"
                    memory: 500M
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 3s
                max_attempts: 0
networks: {}
volumes: {}

